### ISSUE TITLE
See source

### ISSUE THREAD

**Issue by bernaferrari** [pakoito/Komprehensions#1]
Similar to this: https://github.com/Karn/notify/issues/36
![image](https://user-images.githubusercontent.com/351125/55745720-47134d00-5a0e-11e9-862a-30528f0a0ae6.png)

**Comment by pakoito** [comment]
I can accept a PR for them, but the library is pretty much stable otherwise and I don't want to touch the repo much.

**Comment by bernaferrari** [comment]
It is a simple [build.gradle](https://github.com/Karn/notify/pull/38/files#diff-0d1d9100a9b6813b8cb5c470bf313d00) change. So.. do I commit it?

**Comment by pakoito** [comment]
Go for it!

**Comment by pakoito** [comment]
Built: https://jitpack.io/com/github/pakoito/Komprehensions/1.3.1/build.log
